### ISSUE TITLE
No way to modify the MongoDefaults

### ISSUE THREAD

**Issue by aaronpowell** [jageall/IdentityServer.v3.MongoDb#37]
We're hosting our IdSvr in Azure and have hit a problem with the connections being terminated as described here - https://groups.google.com/forum/?fromgroups#!topic/mongodb-user/_Z8YepNHnbI

The recommended solution is that we change the `MongoDefaults.MaxConnectionIdleTime` to be smaller but unfortunately we can't access that static class as it's ILMerged into the assembly and there's no public API from this plugin to set it.

Using reflection I can get to the property and set it which seems to have resolved the problem in our app but I'd prefer to not use reflection to do this. I'd like a way to set the values on the `MongoDefaults` class.

**Comment by jageall** [comment]
Ok, I'll have a look this morning 

Sent from my Windows Phone

-----Original Message-----

**Comment by jageall** [comment]
So i had a play around with this and I think you can set it from the connection string like this : mongodb://localhost/?maxIdleTimeMS=60000 , would that work for you?

**Comment by aaronpowell** [comment]
Oh, didn’t know that that could be done. I’ll remove my reflection hack and try that out

**Comment by jageall** [comment]
if it does work let me know, i am in the middle of writing a quick guide to using the store and will put this in it

**Comment by vsimonian** [comment]
+1 for the guide! I've been fiddling with this library for a day now, and, most likely due to me generally being a blockhead, haven't figured it out just yet.

@jageall You're my hero!

**Comment by aaronpowell** [comment]
Can confirm that adding it to the connection string works as needed ☺
