### ISSUE TITLE
IdentityServerMongoDb missing

### ISSUE THREAD

**Issue by Gentlehag** [jageall/IdentityServer.v3.MongoDb#41]
I wanted to try the example from the start page. but after referencing this package and pasting the code the type  IdentityServerMongoDb could not get resolved. Any naming changes?

**Comment by jageall** [comment]
looks like the example has a '.' missing from the namespace. It should be IdentityServer.MongoDb

**Comment by Gentlehag** [comment]
ok thx that works now . but still igot errors it seems like some refs are not registered in the di. .

What I currently have is this:

```

           var userService = new Registration<IUserService>();
            // Create and modify default settings
            var settings = StoreSettings.DefaultSettings();
            settings.ConnectionString = ConfigurationManager.AppSettings["authdb"];

            // Create the MongoDB factory
            var factory = new ServiceFactory(userService, settings);
            options.Factory = factorty
```

what am I missing?

**Comment by Gentlehag** [comment]
exception message:
:"No constructors on type 'Thinktecture.IdentityServer.Core.Services.IUserService' can be found with the constructor

**Comment by jageall** [comment]
in the first line you need to supply a user service of your own that implements the IUserService interface. this lib only implements the infrastructure for OIDC, not the user store.  To get started IIRC you can use thinktectures in memory user service which allows you to hard code some users to get up and running.

**Comment by Gentlehag** [comment]
ah ok. that was my misunderstanding, i was assuming that this libarary is implementing the persistance of the identitystore entities which are in most examples stored in memory

**Comment by jageall** [comment]
it implements token and client storage as this is generic functionality. User registration is often customised.

**Comment by Gentlehag** [comment]
ok thx wasn't aware of that
