### ISSUE TITLE
IdentityServer3.MongoDb and IdentityServer3.MongoDb.Admin not working together with latest version of both

### ISSUE THREAD

**Issue by VjParmar** [jageall/IdentityServer.v3.MongoDb#43]
Hi,
 i am trying to run one of our solution to add Identity Server Client to mongo Db bu start getting erro after i upgraded idenittyserver3.MongoDb to 2.1.1 same work if i use 2.0.1
i am getting below error
Method not found: 'MongoDB.Driver.ObjectFilterDefinition`1<MongoDB.Bson.BsonDocument> IdentityServer3.MongoDb.Filter.ById(System.Object)'.
![image](https://cloud.githubusercontent.com/assets/25687309/22827548/77cfaa5e-efbe-11e6-90a3-de03ba4d1634.png)

**Comment by jageall** [comment]
yeah, i didn't have time to update admin yet, it is on my todo list for this weekend

**Comment by jageall** [comment]
Ok, part of the problem is that 2.0.1 is a package i thought i had unlisted because the id of the module changed. you want to be using IdentityServer3.MongoDb.Admin version 3.1.0. I have updated that to work with the latest version, please migrate to the new package and let me know if that fixes your issues

**Comment by VjParmar** [comment]
Thanks , it is working now

**Comment by jageall** [comment]
awesome :)

**Comment by VjParmar** [comment]
Hi, i just noticed that even identiyserver3 version alos get updated , is it necessary ? as we started gettting some error in our application after that update of identityserver 2.6 previously it was on 2.4

**Comment by jageall** [comment]
I believe so. what error are you getting?
