### ISSUE TITLE
IdentityServer3 Client not having all the values set

### ISSUE THREAD

**Issue by VjParmar** [jageall/IdentityServer.v3.MongoDb#44]
Hi ,
 i am trying to add client to Mongo Db ,but facing weired issue ,some values are missing while inserting to mongo Db and same are not being read as well if i manually update the Mongo DB Doc.the fields are 

LogoutUri
RequiredSignoutPrompt
LogoutSessionRequired

 i did not find a way to check the logs to understand why only these values are missing .
i am using IdentityServer3.MongoDb 2.0.1 and dentityServer3.MongoDb.Admin 3.0.0
i am not able to use the latest version, i have another issue for same https://github.com/jageall/IdentityServer.v3.MongoDb/issues/43

**Comment by jageall** [comment]
closing this as it relates to the admin module not having been updated which is in #43
